/* eslint-disable sort-keys */
export const TF2_KEYS = [
  'MOUSE1',
  'MOUSE2',
  'MOUSE3',
  'MOUSE4',
  'MOUSE5',
  'MWHEELUP',
  'MWHEELDOWN',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '0',
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
  'F1',
  'F2',
  'F3',
  'F4',
  'F5',
  'F6',
  'F7',
  'F8',
  'F9',
  'F10',
  'F11',
  'F12',
  '`',
  "'",
  '-',
  '=',
  '[',
  ']',
  '\\',
  ',',
  '/',
  'SPACE',
  'ENTER',
  'ESCAPE',
  'PAUSE',
  'BACKSPACE',
  'TAB',
  'SEMICOLON',
  'SHIFT',
  'CTRL',
  'ALT',
  'UPARROW',
  'DOWNARROW',
  'LEFTARROW',
  'RIGHTARROW',
  'INS',
  'HOME',
  'PGUP',
  'PGDN',
  'DEL',
  'END',
  'KP_HOME',
  'KP_UPARROW',
  'KP_PGUP',
  'KP_LEFTARROW',
  'KP_5',
  'KP_RIGHTARROW',
  'KP_END',
  'KP_ENTER',
  'KP_DOWNARROW',
  'KP_PGDN',
  'KP_INS',
  'KP_DEL',
  'KP_SLASH',
  'KP_MINUS',
  'KP_PLUS',
  'KP_MULTIPLY',
];

export const JS_KEYCODES = {
  '8': 'BACKSPACE',
  '9': 'TAB',
  '13': 'ENTER',
  '16': 'SHIFT',
  '17': 'CTRL',
  '18': 'ALT',
  '19': 'PAUSE_BREAK',
  '20': 'CAPSLOCK',
  '27': 'ESCAPE',
  '32': 'SPACE',
  '33': 'PAGEUP',
  '34': 'PAGEDOWN',
  '35': 'END',
  '36': 'HOME',
  '37': 'LEFTARROW',
  '38': 'UPARROW',
  '39': 'RIGHTARROW',
  '40': 'DOWNARROW',
  '45': 'INSERT',
  '46': 'DELETE',
  '48': '0',
  '49': '1',
  '50': '2',
  '51': '3',
  '52': '4',
  '53': '5',
  '54': '6',
  '55': '7',
  '56': '8',
  '57': '9',
  '65': 'A',
  '66': 'B',
  '67': 'C',
  '68': 'D',
  '69': 'E',
  '70': 'F',
  '71': 'G',
  '72': 'H',
  '73': 'I',
  '74': 'J',
  '75': 'K',
  '76': 'L',
  '77': 'M',
  '78': 'N',
  '79': 'O',
  '80': 'P',
  '81': 'Q',
  '82': 'R',
  '83': 'S',
  '84': 'T',
  '85': 'U',
  '86': 'V',
  '87': 'W',
  '88': 'X',
  '89': 'Y',
  '90': 'Z',
  '91': 'LEFT_WINDOW_KEY',
  '92': 'RIGHT_WINDOW_KEY',
  '93': 'SELECT_KEY',
  '96': 'NUMPAD0',
  '97': 'NUMPAD1',
  '98': 'NUMPAD2',
  '99': 'NUMPAD3',
  '100': 'NUMPAD4',
  '101': 'NUMPAD5',
  '102': 'NUMPAD6',
  '103': 'NUMPAD7',
  '104': 'NUMPAD8',
  '105': 'NUMPAD9',
  '106': 'MULTIPLY',
  '107': 'ADD',
  '109': 'SUBTRACT',
  '110': 'DECIMAL_POINT',
  '111': 'DIVIDE',
  '112': 'F1',
  '113': 'F2',
  '114': 'F3',
  '115': 'F4',
  '116': 'F5',
  '117': 'F6',
  '118': 'F7',
  '119': 'F8',
  '120': 'F9',
  '121': 'F10',
  '122': 'F11',
  '123': 'F12',
  '144': 'NUM_LOCK',
  '145': 'SCROLL_LOCK',
  '186': 'SEMI_COLON',
  '187': 'EQUAL_SIGN',
  '188': 'COMMA',
  '189': 'DASH',
  '190': 'PERIOD',
  '191': 'FORWARD_SLASH',
  '192': 'GRAVE_ACCENT',
  '219': 'OPEN_BRACKET',
  '220': 'BACK_SLASH',
  '221': 'CLOSE_BRACKET',
  '222': 'SINGLE_QUOTE',
};

export const JS_KEY_TO_TF2 = {
  Digit1: '1',
  Digit2: '2',
  Digit3: '3',
  Digit4: '4',
  Digit5: '5',
  Digit6: '6',
  Digit7: '7',
  Digit8: '8',
  Digit9: '9',
  Digit0: '0',
  KeyA: 'A',
  KeyB: 'B',
  KeyC: 'C',
  KeyD: 'D',
  KeyE: 'E',
  KeyF: 'F',
  KeyG: 'G',
  KeyH: 'H',
  KeyI: 'I',
  KeyJ: 'J',
  KeyK: 'K',
  KeyL: 'L',
  KeyM: 'M',
  KeyN: 'N',
  KeyO: 'O',
  KeyP: 'P',
  KeyQ: 'Q',
  KeyR: 'R',
  KeyS: 'S',
  KeyT: 'T',
  KeyU: 'U',
  KeyV: 'V',
  KeyW: 'W',
  KeyX: 'X',
  KeyY: 'Y',
  KeyZ: 'Z',
  Backquote: '`',
  Quote: "'",
  Minus: '-',
  Equal: '=',
  BracketLeft: '[',
  BracketRight: ']',
  Backslash: '\\',
  Comma: ',',
  Slash: '/',
  Space: 'SPACE',
  Enter: 'ENTER',
  Escape: 'ESCAPE',
  Pause: 'PAUSE',
  Backspace: 'BACKSPACE',
  Tab: 'TAB',
  Semicolon: 'SEMICOLON',
  Shift: 'SHIFT',
  Control: 'CTRL',
  Alt: 'ALT',
  ArrowUp: 'UPARROW',
  ArrowDown: 'DOWNARROW',
  ArrowLeft: 'LEFTARROW',
  ArrowRight: 'RIGHTARROW',
  Insert: 'INS',
  Home: 'HOME',
  PageUp: 'PGUP',
  PageDown: 'PGDN',
  Delete: 'DEL',
  End: 'END',
  Numpad0: 'KP_INS',
  Numpad1: 'KP_END',
  Numpad2: 'KP_DOWNARROW',
  Numpad3: 'KP_PGDN',
  Numpad4: 'KP_LEFTARROW',
  Numpad5: 'KP_5',
  Numpad6: 'KP_RIGHTARROW',
  Numpad7: 'KP_HOME',
  Numpad8: 'KP_UPARROW',
  Numpad9: 'KP_PGUP',
  NumpadEnter: 'KP_ENTER',
  NumpadDecimal: 'KP_DEL',
  NumpadDivide: 'KP_SLASH',
  NumpadMultiply: 'KP_MULTIPLY',
  NumpadSubtract: 'KP_MINUS',
  NumpadAdd: 'KP_PLUS',
};
